### PR TITLE
fixed 'temporary value dropped while borrowed' error

### PR DESCRIPTION
**Pull request by ahenshaw**
Just removed an un-needed borrow that was causing a compilation error for me.

### CODE REVIEW

**Comment by Aloso** [comment]
Hi @ahenshaw, thanks for contributing! I'm glad that you're interested in this program.

Note that this is fixed in the new feature branch I was just about to merge. There will be a new release soon.

What OS do you use? Since I use Linux and don't have access to a macOS or Windows machine, it would be nice to have Windows or macOS testers who can report OS-specific issues., Let me know if you are open to it.

I'll merge this and rebase my feature branch then 😉

**Comment by ahenshaw** [comment]
Thanks for merging and being so responsive!  

I do primarily use Windows, and I’d be glad to help.  So far, everything is working great!

Andy Henshaw

**Comment by Aloso** [comment]
@ahenshaw I wrote a GitHub workflow to automate releases, so the [new version](https://github.com/Aloso/colo/releases/tag/v0.2.2) includes a Windows binary. Could you check that it works? That would be really appreciated!

**Comment by ahenshaw** [comment]
Ran through all of my examples perfectly!  Nice job!

**Pull request merged**
